apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    release: ngnix
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: {{.Values.replicas}}
  template: 
    metadata:
      labels:
        app: nginx
        release: ngnix
    spec:
      containers:
      - name: nginx
        image: nginx:{{.Values.tag}}
        ports:
        - containerPort: 80
